app:
  service: gemini-poc
  environment: dev
  timezone: "Asia/Makassar"
  shutdownTimeout: 10s
  targetHost: "http://host.docker.internal:8080"
  destinationHost: "http://host.docker.internal:8090"
  proxyTimeout: 10m
  maxMirrorWorker: 10
  maxMirrorWorkerQueue: 1000
  maxMirrorRetry: 
    max: 3
    delay: 500ms
  mirrors:
    - name: "Master"
      methods:
        - "POST"
        - "PUT"
        - "DELETE" 
        - "PATCH"
      endpoints: 
        - "/api/v1/instalasi"
  auth:
    username: superadmin
    password: "123456"

log:
  level: debug
  path: tmp/service.log
  maxSize: 1
  maxBackups: 3
  maxAge: 30

server:
  rest:
    host: 0.0.0.0
    port: 8000
    prefork: false
